[pytest]
markers =
    unit: Модульные тесты
    integration: Интеграционные тесты
    system: Системные тесты
    performance: Нагрузочные тесты
    acceptance: Приёмочные тесты
    validation: Валидационные тесты